// Talaqi demo data + i18n
export const CATEGORIES = [
  { id: 1, ar: "تطوير المواقع", en: "Web Development", count: 84 },
  { id: 2, ar: "تطوير المتاجر الإلكترونية", en: "E-commerce Development", count: 112 },
  { id: 3, ar: "تطوير تطبيقات الجوال", en: "Mobile App Development", count: 67 },
  { id: 4, ar: "تصميم تجربة المستخدم", en: "UI/UX Design", count: 58 },
  { id: 5, ar: "التصميم الجرافيكي", en: "Graphic Design", count: 45 },
  { id: 6, ar: "الهوية التجارية", en: "Branding", count: 51 },
  { id: 7, ar: "التسويق الرقمي", en: "Digital Marketing", count: 93 },
  { id: 8, ar: "إدارة وسائل التواصل", en: "Social Media Management", count: 40 },
  { id: 9, ar: "كتابة المحتوى", en: "Content Writing", count: 33 },
  { id: 10, ar: "التصوير والإنتاج المرئي", en: "Photography & Videography", count: 29 },
  { id: 11, ar: "الاستشارات الإدارية", en: "Business Consulting", count: 24 },
  { id: 12, ar: "المحاسبة", en: "Accounting", count: 18 },
  { id: 13, ar: "الاستشارات القانونية", en: "Legal Consulting", count: 14 },
  { id: 14, ar: "الأمن السيبراني", en: "Cybersecurity", count: 16 },
  { id: 15, ar: "تحليل البيانات", en: "Data Analysis", count: 21 },
  { id: 16, ar: "حلول الذكاء الاصطناعي", en: "AI Solutions", count: 38 },
];

export const PROVIDERS = [
  { id: 1, ar: "عبدالله الشمري", en: "Abdullah Al-Shammari", typeAr: "مستقل", typeEn: "Freelancer", roleAr: "مطور متاجر إلكترونية", roleEn: "E-commerce Developer", cityAr: "الرياض", cityEn: "Riyadh", skills: ["Shopify", "WooCommerce", "Payment Integration", "UI/UX"], rating: 4.9, min: 4000, max: 9000, years: 7, availAr: "متاح الآن", availEn: "Available now", langs: "AR / EN", verified: true, color: "#1B3568", init: "ع" },
  { id: 2, ar: "وكالة نُقطة الرقمية", en: "Nuqta Digital Agency", typeAr: "وكالة", typeEn: "Agency", roleAr: "حلول تجارة إلكترونية متكاملة", roleEn: "Full-service e-commerce", cityAr: "جدة", cityEn: "Jeddah", skills: ["E-commerce", "Branding", "SEO", "Content"], rating: 4.8, min: 7000, max: 20000, years: 9, availAr: "متاح خلال أسبوع", availEn: "Available in 1 week", langs: "AR / EN", verified: true, color: "#14969E", init: "ن" },
  { id: 3, ar: "محمد العتيبي", en: "Mohammed Al-Otaibi", typeAr: "مستقل", typeEn: "Freelancer", roleAr: "مطور Shopify معتمد", roleEn: "Certified Shopify Developer", cityAr: "جدة", cityEn: "Jeddah", skills: ["Shopify", "Liquid", "Apps Integration"], rating: 4.7, min: 3500, max: 7000, years: 5, availAr: "متاح الآن", availEn: "Available now", langs: "AR / EN", verified: true, color: "#C6A15B", init: "م" },
  { id: 4, ar: "استوديو بِكسل العربية", en: "Pixel Arabia Studio", typeAr: "وكالة", typeEn: "Agency", roleAr: "تصميم واجهات وتجربة مستخدم", roleEn: "UI/UX design studio", cityAr: "الرياض", cityEn: "Riyadh", skills: ["UI/UX", "Design Systems", "Prototyping"], rating: 4.8, min: 5000, max: 15000, years: 6, availAr: "متاح الآن", availEn: "Available now", langs: "AR / EN", verified: true, color: "#1B3568", init: "ب" },
  { id: 5, ar: "شركة تِقنية الحلول", en: "Tiqnia Solutions", typeAr: "شركة", typeEn: "Company", roleAr: "تطوير برمجيات وتكاملات", roleEn: "Software & integrations", cityAr: "الدمام", cityEn: "Dammam", skills: ["Web Dev", "APIs", "Payment Integration"], rating: 4.6, min: 8000, max: 30000, years: 11, availAr: "متاح خلال أسبوعين", availEn: "Available in 2 weeks", langs: "AR / EN", verified: true, color: "#14969E", init: "ت" },
  { id: 6, ar: "ريم العنزي", en: "Reem Al-Anazi", typeAr: "مستقلة", typeEn: "Freelancer", roleAr: "مصورة منتجات تجارية", roleEn: "Product Photographer", cityAr: "الرياض", cityEn: "Riyadh", skills: ["Product Photography", "Retouching"], rating: 4.9, min: 1500, max: 4000, years: 4, availAr: "متاحة الآن", availEn: "Available now", langs: "AR", verified: true, color: "#C6A15B", init: "ر" },
  { id: 7, ar: "سارة القحطاني", en: "Sarah Al-Qahtani", typeAr: "مستقلة", typeEn: "Freelancer", roleAr: "مصممة UI/UX", roleEn: "UI/UX Designer", cityAr: "الرياض", cityEn: "Riyadh", skills: ["Figma", "UI/UX", "Mobile Design"], rating: 4.8, min: 3000, max: 8000, years: 6, availAr: "متاحة الآن", availEn: "Available now", langs: "AR / EN", verified: true, color: "#1B3568", init: "س" },
  { id: 8, ar: "مؤسسة رُؤى للتسويق", en: "Ruaa Marketing", typeAr: "شركة", typeEn: "Company", roleAr: "تسويق رقمي وحملات", roleEn: "Digital marketing & campaigns", cityAr: "الرياض", cityEn: "Riyadh", skills: ["Digital Marketing", "Media Buying", "Analytics"], rating: 4.5, min: 4000, max: 18000, years: 8, availAr: "متاح الآن", availEn: "Available now", langs: "AR / EN", verified: true, color: "#14969E", init: "ر" },
  { id: 9, ar: "نورة الدوسري", en: "Noura Al-Dossari", typeAr: "مستقلة", typeEn: "Freelancer", roleAr: "كاتبة محتوى تسويقي", roleEn: "Marketing Copywriter", cityAr: "الخبر", cityEn: "Khobar", skills: ["Copywriting", "SEO Content", "Arabic Content"], rating: 4.7, min: 1000, max: 3500, years: 5, availAr: "متاحة الآن", availEn: "Available now", langs: "AR / EN", verified: false, color: "#C6A15B", init: "ن" },
  { id: 10, ar: "لمسة إبداع للهوية", en: "Lamsat Ibdaa Branding", typeAr: "وكالة", typeEn: "Agency", roleAr: "هوية بصرية وعلامات تجارية", roleEn: "Branding & identity", cityAr: "جدة", cityEn: "Jeddah", skills: ["Branding", "Logo Design", "Guidelines"], rating: 4.6, min: 3000, max: 12000, years: 7, availAr: "متاح خلال أسبوع", availEn: "Available in 1 week", langs: "AR", verified: true, color: "#1B3568", init: "ل" },
  { id: 11, ar: "فهد الحربي", en: "Fahad Al-Harbi", typeAr: "مستشار", typeEn: "Consultant", roleAr: "مستشار تطوير أعمال", roleEn: "Business Consultant", cityAr: "الرياض", cityEn: "Riyadh", skills: ["Strategy", "Feasibility", "Operations"], rating: 4.8, min: 5000, max: 15000, years: 12, availAr: "متاح الآن", availEn: "Available now", langs: "AR / EN", verified: true, color: "#14969E", init: "ف" },
  { id: 12, ar: "مِعمار الرقمية", en: "Miamar Digital", typeAr: "وكالة", typeEn: "Agency", roleAr: "تطوير تطبيقات ومنصات", roleEn: "Apps & platforms", cityAr: "دبي", cityEn: "Dubai", skills: ["Flutter", "React Native", "Backend"], rating: 4.7, min: 15000, max: 60000, years: 10, availAr: "متاح خلال شهر", availEn: "Available in 1 month", langs: "AR / EN", verified: true, color: "#1B3568", init: "م" },
  { id: 13, ar: "خالد باوزير", en: "Khalid Bawazeer", typeAr: "مستشار", typeEn: "Consultant", roleAr: "محاسب قانوني معتمد", roleEn: "Certified Accountant", cityAr: "جدة", cityEn: "Jeddah", skills: ["Accounting", "Zakat & Tax", "Audit"], rating: 4.9, min: 2000, max: 8000, years: 14, availAr: "متاح الآن", availEn: "Available now", langs: "AR / EN", verified: true, color: "#C6A15B", init: "خ" },
  { id: 14, ar: "داتا لينس للتحليلات", en: "DataLens Analytics", typeAr: "شركة", typeEn: "Company", roleAr: "تحليل بيانات ولوحات معلومات", roleEn: "Data & dashboards", cityAr: "الرياض", cityEn: "Riyadh", skills: ["Power BI", "Python", "Data Modeling"], rating: 4.6, min: 6000, max: 25000, years: 6, availAr: "متاح خلال أسبوع", availEn: "Available in 1 week", langs: "AR / EN", verified: false, color: "#14969E", init: "د" },
  { id: 15, ar: "هند الزهراني", en: "Hind Al-Zahrani", typeAr: "مستقلة", typeEn: "Freelancer", roleAr: "إدارة وسائل التواصل الاجتماعي", roleEn: "Social Media Manager", cityAr: "مكة", cityEn: "Makkah", skills: ["Social Media", "Content Calendar", "Community"], rating: 4.5, min: 1500, max: 5000, years: 4, availAr: "متاحة الآن", availEn: "Available now", langs: "AR", verified: false, color: "#1B3568", init: "هـ" },
  { id: 16, ar: "أمان السيبرانية", en: "Aman Cybersecurity", typeAr: "شركة", typeEn: "Company", roleAr: "أمن سيبراني واختبار اختراق", roleEn: "Security & pentesting", cityAr: "الرياض", cityEn: "Riyadh", skills: ["Pentesting", "Compliance", "SOC"], rating: 4.8, min: 10000, max: 45000, years: 8, availAr: "متاح خلال أسبوعين", availEn: "Available in 2 weeks", langs: "AR / EN", verified: true, color: "#14969E", init: "أ" },
];

// Match results for the perfume store demo project
export const MATCHES = [
  { pid: 1, score: 94, reasonAr: "خبرة مباشرة في متاجر العطور والتجميل مع تكامل بوابات الدفع السعودية", reasonEn: "Direct experience with perfume/beauty stores and Saudi payment gateways" },
  { pid: 2, score: 91, reasonAr: "وكالة متكاملة تغطي التصميم والتطوير والمحتوى ضمن ميزانيتك", reasonEn: "Full-service agency covering design, build and content within budget" },
  { pid: 3, score: 88, reasonAr: "مطور Shopify معتمد بأسعار متوافقة تمامًا مع الميزانية المقترحة", reasonEn: "Certified Shopify developer priced squarely within your budget" },
  { pid: 4, score: 84, reasonAr: "تصميم واجهات فاخرة يناسب طبيعة منتجات العطور الراقية", reasonEn: "Premium UI design suited to luxury perfume products" },
  { pid: 5, score: 79, reasonAr: "قدرة قوية على التكاملات التقنية، لكن الأسعار أعلى من النطاق", reasonEn: "Strong integrations capability, though pricing runs above range" },
  { pid: 6, score: 76, reasonAr: "تصوير احترافي للمنتجات — مكمّل مثالي لإطلاق المتجر", reasonEn: "Professional product photography — ideal launch complement" },
];

export const PROJECTS = [
  { id: 1, titleAr: "متجر إلكتروني لبيع العطور", titleEn: "Perfume e-commerce store", catAr: "تجارة إلكترونية", catEn: "E-commerce", status: "matched", budget: "4,000–8,000", timelineAr: "3–5 أسابيع", timelineEn: "3–5 weeks", date: "2026/06/28" },
  { id: 2, titleAr: "هوية بصرية لمقهى مختص", titleEn: "Specialty café brand identity", catAr: "هوية تجارية", catEn: "Branding", status: "completed", budget: "3,500–6,000", timelineAr: "أسبوعان", timelineEn: "2 weeks", date: "2026/05/12" },
  { id: 3, titleAr: "حملة تسويقية لموسم الرياض", titleEn: "Riyadh Season campaign", catAr: "تسويق رقمي", catEn: "Marketing", status: "inprogress", budget: "12,000–18,000", timelineAr: "6 أسابيع", timelineEn: "6 weeks", date: "2026/06/02" },
  { id: 4, titleAr: "تطبيق حجز مواعيد صالونات", titleEn: "Salon booking app", catAr: "تطبيقات جوال", catEn: "Mobile Apps", status: "draft", budget: "—", timelineAr: "—", timelineEn: "—", date: "2026/07/01" },
  { id: 5, titleAr: "لوحة تحليلات للمبيعات", titleEn: "Sales analytics dashboard", catAr: "تحليل بيانات", catEn: "Data Analysis", status: "brief", budget: "6,000–10,000", timelineAr: "4 أسابيع", timelineEn: "4 weeks", date: "2026/06/20" },
];

// Provider-side opportunities
export const OPPORTUNITIES = [
  { id: 1, titleAr: "متجر إلكتروني لبيع العطور", titleEn: "Perfume e-commerce store", score: 94, budget: "4,000–8,000", timelineAr: "3–5 أسابيع", timelineEn: "3–5 weeks", skills: ["Shopify", "Payment Integration", "UI/UX"], clientAr: "شركة عود الخليج", clientEn: "Oud Al-Khaleej Co.", noteAr: "ملخص مشروع معتمد من العميل — نطاق عمل واضح و13 بندًا محددًا", noteEn: "Client-approved brief — clear scope with 13 defined items" },
  { id: 2, titleAr: "متجر أدوات قهوة مختصة", titleEn: "Specialty coffee gear store", score: 87, budget: "6,000–11,000", timelineAr: "4 أسابيع", timelineEn: "4 weeks", skills: ["WooCommerce", "Shipping APIs"], clientAr: "مؤسسة كوب الصباح", clientEn: "Morning Cup Est.", noteAr: "يتطلب ربط شحن مع 3 شركات محلية", noteEn: "Requires integration with 3 local carriers" },
  { id: 3, titleAr: "تحويل متجر قائم إلى Shopify Plus", titleEn: "Migration to Shopify Plus", score: 81, budget: "15,000–25,000", timelineAr: "8 أسابيع", timelineEn: "8 weeks", skills: ["Shopify Plus", "Data Migration"], clientAr: "دار الأناقة للأزياء", clientEn: "Dar Al-Anaqa Fashion", noteAr: "متجر قائم بأكثر من 2,000 منتج", noteEn: "Existing store with 2,000+ products" },
];

export const ADMIN = {
  users: 1284, clients: 942, providers: 326, projects: 418, weekly: 37,
  briefs: 389, pending: 12, matchRate: 87,
  topCats: [
    { ar: "تجارة إلكترونية", en: "E-commerce", v: 112 },
    { ar: "تسويق رقمي", en: "Digital Marketing", v: 93 },
    { ar: "تطوير مواقع", en: "Web Development", v: 84 },
    { ar: "تطبيقات جوال", en: "Mobile Apps", v: 67 },
    { ar: "UI/UX", en: "UI/UX", v: 58 },
    { ar: "هوية تجارية", en: "Branding", v: 51 },
  ],
  pendingProviders: [
    { ar: "ماجد السبيعي — مطور واجهات", en: "Majed Al-Subaie — Frontend Dev", cityAr: "الرياض", cityEn: "Riyadh", d: "2026/07/01" },
    { ar: "استوديو ضوء للإنتاج", en: "Dhaw Production Studio", cityAr: "جدة", cityEn: "Jeddah", d: "2026/06/30" },
    { ar: "أريج الغامدي — مصممة جرافيك", en: "Areej Al-Ghamdi — Graphic Designer", cityAr: "أبها", cityEn: "Abha", d: "2026/06/29" },
    { ar: "شركة نمو للاستشارات", en: "Numou Consulting", cityAr: "الرياض", cityEn: "Riyadh", d: "2026/06/28" },
  ],
};

// Scripted AI conversation — perfume store demo
export const CHAT_SCRIPT = [
  {
    qAr: "هلا فيك، وصلني وش تبي بالضبط. عشان أجهّز لك ملخص تنفيذي دقيق، قول لي أول شي: وش نوع المنتجات اللي بتبيعها، وكم عددها تقريبًا عند الإطلاق؟",
    qEn: "Welcome — I understand your need clearly. To prepare an accurate brief, first: what products will you sell, and roughly how many at launch?",
    chips: [
      { ar: "عطور نسائية ورجالية، تقريبًا 50 منتج", en: "Men's & women's perfumes, ~50 products" },
      { ar: "عطور ودهن عود فاخر، 120 منتج", en: "Perfumes & luxury oud, 120 products" },
    ],
  },
  {
    qAr: "تمام. عندك هوية بصرية جاهزة (شعار وألوان)، ولا تبي نصمّم لك هوية ضمن المشروع؟",
    qEn: "Great. Do you have a ready brand identity (logo & colors), or should identity design be part of the scope?",
    chips: [
      { ar: "عندي هوية جاهزة", en: "I have a ready identity" },
      { ar: "أبي تصميم هوية كاملة", en: "I need full identity design" },
    ],
  },
  {
    qAr: "واضح. بالنسبة للدفع والشحن: تبي بوابة دفع (مدى، Apple Pay، STC Pay) وربط مع شركات الشحن المحلية؟",
    qEn: "Understood. For payments & shipping: do you need a payment gateway (mada, Apple Pay, STC Pay) and local carrier integration?",
    chips: [
      { ar: "إي، دفع إلكتروني وربط شحن كامل", en: "Yes — full payments & shipping" },
      { ar: "دفع إلكتروني بس حاليًا", en: "Payments only for now" },
    ],
  },
  {
    qAr: "تمام. كم الميزانية اللي حاطها تقريبًا للمشروع؟",
    qEn: "Very good. What approximate budget have you allocated?",
    chips: [
      { ar: "بين 4,000 و 8,000 ريال", en: "Between 4,000–8,000 SAR" },
      { ar: "أقل من 4,000 ريال", en: "Under 4,000 SAR" },
      { ar: "أكثر من 10,000 ريال", en: "Over 10,000 SAR" },
    ],
  },
  {
    qAr: "آخر سؤال: متى ودّك تطلق المتجر؟",
    qEn: "Last question: when do you aim to launch?",
    chips: [
      { ar: "خلال شهر تقريبًا", en: "Within about a month" },
      { ar: "خلال أسبوعين — مستعجل", en: "Within 2 weeks — urgent" },
      { ar: "ما فيه موعد محدد", en: "No fixed date" },
    ],
  },
];

export const CHAT_DONE = {
  ar: "الصورة صارت واضحة عندي. جمعت 9 متطلبات أساسية وحددت نطاق العمل والمهارات المطلوبة. جاهز أطلّع لك الملخص التنفيذي للمشروع.",
  en: "I have the full picture — 9 core requirements captured, scope and skills identified. Ready to generate your Project Brief.",
};

export const BRIEF = {
  titleAr: "متجر إلكتروني لبيع العطور", titleEn: "Perfume E-commerce Store",
  summaryAr: "بناء متجر إلكتروني احترافي لبيع العطور النسائية والرجالية (~50 منتجًا عند الإطلاق) بهوية بصرية جاهزة، مع بوابة دفع محلية وربط كامل مع شركات الشحن، خلال مدة لا تتجاوز خمسة أسابيع.",
  summaryEn: "Build a professional e-commerce store for men's & women's perfumes (~50 products at launch) using an existing brand identity, with local payment gateway and full shipping integration, delivered within five weeks.",
  objectiveAr: "إطلاق قناة بيع رقمية مباشرة ترفع المبيعات وتوسّع الوصول لعملاء جدد داخل المملكة.",
  objectiveEn: "Launch a direct digital sales channel to grow revenue and reach new customers across KSA.",
  scopeAr: ["تصميم واجهة المتجر بما يتوافق مع الهوية الحالية", "تطوير المتجر وإعداد بنية الأقسام", "إضافة وتهيئة 50 منتجًا", "تكامل بوابة دفع (مدى، Apple Pay، STC Pay)", "ربط شركات الشحن المحلية", "تدريب وتسليم لوحة الإدارة"],
  scopeEn: ["Storefront design aligned with existing identity", "Store development & catalog structure", "Setup of 50 products", "Payment gateway integration (mada, Apple Pay, STC Pay)", "Local shipping carriers integration", "Admin training & handover"],
  deliverablesAr: ["متجر إلكتروني جاهز للإطلاق", "لوحة إدارة مهيأة", "دليل تشغيل مختصر", "شهر دعم فني"],
  deliverablesEn: ["Launch-ready online store", "Configured admin panel", "Short operations guide", "One month technical support"],
  skills: ["E-commerce", "UI/UX", "Payment Integration", "Shopify / WooCommerce", "Shipping APIs"],
  budget: "4,000 – 8,000", budgetUnitAr: "ريال سعودي", budgetUnitEn: "SAR",
  timelineAr: "3 – 5 أسابيع", timelineEn: "3–5 weeks",
  complexityAr: "متوسطة", complexityEn: "Medium", complexityPct: 55,
  missingAr: ["هل تتوفر صور احترافية للمنتجات؟", "هل يتطلب المتجر لغة إنجليزية إضافية؟"],
  missingEn: ["Are professional product photos available?", "Is an English storefront required?"],
  providerTypeAr: "مطور متاجر إلكترونية أو وكالة رقمية صغيرة",
  providerTypeEn: "E-commerce developer or small digital agency",
  criteriaAr: ["خبرة سابقة في متاجر العطور أو التجميل", "تقييم 4.5 فأعلى", "التزام بالجدول الزمني", "دعم ما بعد الإطلاق"],
  criteriaEn: ["Prior perfume/beauty store experience", "Rating 4.5+", "Timeline commitment", "Post-launch support"],
  milestonesAr: [
    { t: "الأسبوع 1", d: "تصميم الواجهات واعتمادها" },
    { t: "الأسبوع 2–3", d: "تطوير المتجر وإضافة المنتجات" },
    { t: "الأسبوع 4", d: "تكامل الدفع والشحن والاختبار" },
    { t: "الأسبوع 5", d: "الإطلاق والتدريب والتسليم" },
  ],
  milestonesEn: [
    { t: "Week 1", d: "UI design & approval" },
    { t: "Weeks 2–3", d: "Store build & product setup" },
    { t: "Week 4", d: "Payments, shipping & QA" },
    { t: "Week 5", d: "Launch, training & handover" },
  ],
};

export const USERS = [
  { ar: "أحمد المطيري", en: "Ahmed Al-Mutairi", email: "ahmed@oudalkhaleej.sa", role: "client", joined: "2026/03/14", active: true },
  { ar: "عبدالله الشمري", en: "Abdullah Al-Shammari", email: "abdullah.dev@gmail.com", role: "provider", joined: "2025/11/02", active: true },
  { ar: "سارة القحطاني", en: "Sarah Al-Qahtani", email: "sarah.design@outlook.com", role: "provider", joined: "2025/12/18", active: true },
  { ar: "منى الراشد", en: "Muna Al-Rashed", email: "muna@nooncafe.sa", role: "client", joined: "2026/01/22", active: true },
  { ar: "وكالة نُقطة الرقمية", en: "Nuqta Digital Agency", email: "hello@nuqta.sa", role: "provider", joined: "2025/10/05", active: true },
  { ar: "بدر الغامدي", en: "Badr Al-Ghamdi", email: "badr@rswn.sa", role: "client", joined: "2026/02/09", active: true },
  { ar: "ريم العنزي", en: "Reem Al-Anazi", email: "reem.photo@gmail.com", role: "provider", joined: "2026/01/30", active: true },
  { ar: "مؤسسة كوب الصباح", en: "Morning Cup Est.", email: "info@morningcup.sa", role: "client", joined: "2026/04/11", active: true },
  { ar: "طارق حسن", en: "Tariq Hassan", email: "tariq.h@yahoo.com", role: "client", joined: "2026/05/03", active: false },
  { ar: "فريق تلاقي", en: "Talaqi Team", email: "ops@talaqi.sa", role: "admin", joined: "2025/09/01", active: true },
];

export const REQUESTS = [
  { id: 1, projAr: "متجر إلكتروني لبيع العطور", projEn: "Perfume e-commerce store", clientAr: "شركة عود الخليج", clientEn: "Oud Al-Khaleej Co.", budget: "4,000–8,000", timelineAr: "3–5 أسابيع", timelineEn: "3–5 weeks", whenAr: "قبل 10 دقائق", whenEn: "10 minutes ago", noteAr: "يرغب العميل بالبدء خلال أسبوع من اختيار المقدم", noteEn: "Client wants to start within a week of selection" },
  { id: 2, projAr: "متجر أدوات قهوة مختصة", projEn: "Specialty coffee gear store", clientAr: "مؤسسة كوب الصباح", clientEn: "Morning Cup Est.", budget: "6,000–11,000", timelineAr: "4 أسابيع", timelineEn: "4 weeks", whenAr: "قبل 3 ساعات", whenEn: "3 hours ago", noteAr: "مطلوب ربط شحن مع 3 شركات محلية", noteEn: "Requires integration with 3 local carriers" },
  { id: 3, projAr: "تجديد متجر أزياء قائم", projEn: "Fashion store revamp", clientAr: "دار الأناقة للأزياء", clientEn: "Dar Al-Anaqa Fashion", budget: "15,000–25,000", timelineAr: "8 أسابيع", timelineEn: "8 weeks", whenAr: "أمس", whenEn: "Yesterday", noteAr: "متجر قائم بأكثر من 2,000 منتج — يتطلب نقل بيانات", noteEn: "Existing store with 2,000+ products — data migration needed" },
];

export const BRIEFS_LIST = [
  { titleAr: "متجر إلكتروني لبيع العطور", titleEn: "Perfume e-commerce store", clientAr: "شركة عود الخليج", clientEn: "Oud Al-Khaleej Co.", catAr: "تجارة إلكترونية", catEn: "E-commerce", date: "2026/06/28", q: 96, approved: true },
  { titleAr: "متجر أدوات قهوة مختصة", titleEn: "Specialty coffee gear store", clientAr: "مؤسسة كوب الصباح", clientEn: "Morning Cup Est.", catAr: "تجارة إلكترونية", catEn: "E-commerce", date: "2026/06/25", q: 92, approved: true },
  { titleAr: "تطبيق حجز مواعيد صالونات", titleEn: "Salon booking app", clientAr: "بدر الغامدي", clientEn: "Badr Al-Ghamdi", catAr: "تطبيقات جوال", catEn: "Mobile Apps", date: "2026/07/01", q: 88, approved: false },
  { titleAr: "لوحة تحليلات للمبيعات", titleEn: "Sales analytics dashboard", clientAr: "منى الراشد", clientEn: "Muna Al-Rashed", catAr: "تحليل بيانات", catEn: "Data Analysis", date: "2026/06/20", q: 91, approved: true },
  { titleAr: "هوية بصرية لمقهى مختص", titleEn: "Specialty café brand identity", clientAr: "منى الراشد", clientEn: "Muna Al-Rashed", catAr: "هوية تجارية", catEn: "Branding", date: "2026/05/12", q: 85, approved: true },
];

export const ANALYTICS = {
  avg: 86, accept: 74, timeAr: "3.2 دقيقة", timeEn: "3.2 min",
  dist: [
    { rAr: "90 – 100", rEn: "90 – 100", v: 38 },
    { rAr: "80 – 89", rEn: "80 – 89", v: 31 },
    { rAr: "70 – 79", rEn: "70 – 79", v: 19 },
    { rAr: "أقل من 70", rEn: "Below 70", v: 12 },
  ],
  weekly: {
    daysAr: ["أحد", "اثنين", "ثلاثاء", "أربعاء", "خميس", "جمعة", "سبت"],
    daysEn: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    v: [6, 9, 5, 11, 8, 3, 4],
  },
  rev: { mrr: "48,500", subs: "214", growth: "+18%" },
};

export const SKILLS = [
  { n: "Shopify", cAr: "تجارة إلكترونية", cEn: "E-commerce" },
  { n: "WooCommerce", cAr: "تجارة إلكترونية", cEn: "E-commerce" },
  { n: "Payment Integration", cAr: "تجارة إلكترونية", cEn: "E-commerce" },
  { n: "Shipping APIs", cAr: "تجارة إلكترونية", cEn: "E-commerce" },
  { n: "React", cAr: "تطوير مواقع", cEn: "Web Dev" },
  { n: "Flutter", cAr: "تطبيقات جوال", cEn: "Mobile" },
  { n: "Figma", cAr: "تصميم", cEn: "Design" },
  { n: "UI/UX", cAr: "تصميم", cEn: "Design" },
  { n: "Motion Design", cAr: "تصميم", cEn: "Design" },
  { n: "Logo Design", cAr: "هوية تجارية", cEn: "Branding" },
  { n: "Brand Guidelines", cAr: "هوية تجارية", cEn: "Branding" },
  { n: "SEO", cAr: "تسويق رقمي", cEn: "Marketing" },
  { n: "Media Buying", cAr: "تسويق رقمي", cEn: "Marketing" },
  { n: "Copywriting", cAr: "محتوى", cEn: "Content" },
  { n: "Product Photography", cAr: "تصوير", cEn: "Photography" },
  { n: "Video Editing", cAr: "تصوير", cEn: "Photography" },
  { n: "Power BI", cAr: "تحليل بيانات", cEn: "Data" },
  { n: "Python", cAr: "تحليل بيانات", cEn: "Data" },
  { n: "Pentesting", cAr: "أمن سيبراني", cEn: "Security" },
  { n: "Zakat & Tax", cAr: "محاسبة", cEn: "Accounting" },
];

export const I18N = {
  ar: {
    dir: "rtl", langBtn: "EN",
    brand: "تلاقي", tagline: "ذكاء يوصّلك بالخبرة اللي تناسبك",
    // nav
    navHow: "كيف يشتغل", navFeatures: "المميزات", navCats: "التصنيفات", navPricing: "الاشتراكات", login: "تسجيل الدخول", startCta: "سجّل الآن", joinCta: "انضم كمقدم خدمة",
    // hero
    heroBadge: "منصة الذكاء الاصطناعي للشراء والتنفيذ — Talaqi AI",
    heroTitle1: "بس وصف اللي تبيه،", heroTitle2: "والذكاء الاصطناعي يكمّل الباقي",
    heroSub: "تلاقي منصة ذكية للشراء والتنفيذ، تحوّل اللي تبيه إلى مشروع واضح جاهز للتنفيذ، وبعدها ترشّح لك أنسب مقدم خدمة — بدون بحث ولا مقارنة ولا تعب.",
    heroSubEn: "Talaqi is an AI Procurement & Execution Platform that turns your service needs into clear projects and matches you with the right provider.",
    pipe1: "وصف اللي تبيه", pipe2: "الذكاء يفهم", pipe3: "ملخص تنفيذي", pipe4: "ترشيح ذكي", pipe5: "ابدأ التنفيذ",
    statBriefs: "ملخص تنفيذي مولّد", statProviders: "مقدم خدمة موثّق", statMatch: "دقة التوافق",
    // problem / solution
    problemTitle: "الطريقة التقليدية تاكل وقتك", problemSub: "المنصات الحالية تحطّ حمل الشغل كله على العميل",
    problems: ["تدوّر بنفسك بين مئات المستقلين والشركات", "تقارن الأسعار وتقرأ التقييمات وحدة وحدة", "تكتب وصف المشروع وتقدّر الميزانية بدون خبرة", "تختار في الأخير وتتحمّل مخاطر التنفيذ بروحك"],
    solutionTitle: "تلاقي يقلب المعادلة", solutionSub: "رحلة جديدة تبدأ من الفهم وتوصل للتنفيذ",
    oldJourney: "الرحلة القديمة", newJourney: "رحلة تلاقي",
    oldSteps: "دوّر ← قارن ← اختر", newSteps: "وصف ← الذكاء يفهم ← الذكاء يرشّح ← نفّذ",
    positioning: "تلاقي نظام تشغيل ذكي للخدمات المهنية، يبدأ من فهم احتياج العميل ويوصل لترشيح أنسب مقدم خدمة.",
    // how it works
    howTitle: "تلاقي كيف يشتغل؟", howSub: "خمس خطوات من الفكرة للتنفيذ",
    how: [
      { t: "وصف اللي تبيه", d: "اكتب اللي تحتاجه بلغتك العادية، بدون مصطلحات تقنية" },
      { t: "أسئلة ذكية", d: "الذكاء الاصطناعي يسألك أسئلة مركّزة عشان تكتمل الصورة" },
      { t: "ملخص تنفيذي احترافي", d: "نطاق عمل وميزانية ومدة تنفيذ ومعايير تقييم واضحة" },
      { t: "ترشيح أنسب مقدمي الخدمة", d: "محرك التوافق يرشّح لك الأنسب مع نسبة توافق وسبب واضح" },
      { t: "ابدأ التنفيذ بوضوح", d: "مشروع موثّق ومراحل محددة من أول يوم" },
    ],
    // value
    valueTitle: "قيمة واضحة للطرفين",
    forClients: "للعملاء", forProviders: "لمقدمي الخدمة",
    clientVals: ["جهد أقل ووقت أوفر", "نطاق عمل واضح من البداية", "اختيار أدق لمقدم الخدمة", "مخاطر أقل وتنفيذ أسرع"],
    providerVals: ["طلبات مشاريع واضحة وموثّقة", "فرص تناسب تخصصك", "وقت أقل في العروض الضايعة", "عملاء أكثر جدية"],
    // features
    featuresTitle: "منظومة متكاملة تشتغل بالذكاء الاصطناعي", featuresSub: "من فهم احتياجك إلى ترشيح الأنسب لك",
    features: [
      { t: "تحليل المتطلبات", d: "فهم عميق للاحتياج من وصف بسيط" },
      { t: "مولّد الملخص التنفيذي", d: "ملخص مشروع احترافي من 13 بندًا" },
      { t: "بناء نطاق العمل", d: "مهام ومخرجات محددة قابلة للقياس" },
      { t: "تقدير الميزانية", d: "نطاق سعري واقعي من بيانات السوق" },
      { t: "تقدير المدة الزمنية", d: "جدول تنفيذ ومراحل واضحة" },
      { t: "محرك التوافق الذكي", d: "ترشيح بنسبة توافق وسبب مُعلَّل" },
      { t: "ملفات مقدمي الخدمة", d: "خبرات موثقة وأعمال سابقة وتقييمات" },
      { t: "لوحة مراجعة إدارية", d: "جودة المخرجات تحت إشراف مستمر" },
    ],
    // categories
    catsTitle: "تصنيفات الخدمات", catsSub: "16 تصنيف مهني يغطّي احتياجات الأعمال", catProject: "مشروع",
    // pricing
    pricingTitle: "خطط تناسب كل مرحلة", pricingSub: "ابدأ ببلاش، وترقّى وقت ما تحتاج",
    plans: [
      { n: "مجاني", p: "0", per: "ريال/شهريًا", feats: ["إنشاء طلب مشروع أساسي", "ملخص تنفيذي مبسّط", "ترشيحات محدودة"], cta: "ابدأ ببلاش", hot: false },
      { n: "عميل برو", p: "99", per: "ريال/شهريًا", feats: ["ملخص تنفيذي متقدم", "تقدير الميزانية والمدة", "ترشيحات أوسع", "أولوية في التوافق"], cta: "اشترك الآن", hot: true },
      { n: "أعمال", p: "349", per: "ريال/شهريًا", feats: ["مشاريع متعددة", "وصول للفريق", "لوحة تحكم متقدمة", "مساعد شراء ذكي", "دعم مخصص"], cta: "تواصل معنا", hot: false },
      { n: "مقدم خدمة برو", p: "149", per: "ريال/شهريًا", feats: ["ملف معزّز", "ظهور أعلى", "تحليلات التوافق", "تحسين ملف الأعمال"], cta: "انضم الآن", hot: false },
    ],
    popular: "الأكثر طلبًا",
    // closing
    closingTitle: "يلا ابدأ الحين وحوّل فكرتك إلى مشروع واضح جاهز للتنفيذ",
    closingSub: "دقايق معدودة تفصلك عن ملخص تنفيذي احترافي وأنسب مقدم خدمة",
    footerRights: "© 2026 تلاقي — جميع الحقوق محفوظة", footerMade: "صُنع في المملكة العربية السعودية 🇸🇦",
    footerLinks1: "المنصة", footerLinks2: "الشركة", footerAbout: "عن تلاقي", footerContact: "تواصل معنا", footerTerms: "الشروط والأحكام", footerPrivacy: "سياسة الخصوصية",
    // app shell
    roleClient: "عميل", roleProvider: "مقدم خدمة", roleAdmin: "إدارة", backToSite: "الموقع التعريفي", demoMode: "نسخة تجريبية للعرض",
    // client sidebar
    cNavHome: "لوحة التحكم", cNavNew: "مشروع جديد", cNavBrief: "الملخص التنفيذي", cNavMatches: "مقدمو الخدمة المرشحون", cNavProjects: "مشاريعي", cNavSettings: "الإعدادات",
    clientName: "شركة عود الخليج", clientPerson: "أحمد المطيري",
    welcome: "هلا أحمد 👋", welcomeSub: "خلّنا نحوّل احتياجك الجاي إلى مشروع واضح",
    statActive: "مشاريع نشطة", statBriefsDone: "ملخصات مولّدة", statProposals: "عروض مستلمة", statSaved: "ساعات موفّرة",
    newProjectCta: "ابدأ مشروع جديد", newProjectSub: "بس وصف اللي تبيه والذكاء الاصطناعي يكمّل الباقي",
    myProjects: "مشاريعي", viewAll: "عرض الكل",
    thProject: "المشروع", thCategory: "التصنيف", thBudget: "الميزانية (ريال)", thTimeline: "المدة", thStatus: "الحالة", thDate: "التاريخ",
    stDraft: "مسودة", stBrief: "ملخص مولّد", stMatched: "مرشحون جاهزون", stSelected: "تم اختيار مقدم", stInprogress: "قيد التنفيذ", stCompleted: "مكتمل",
    // chat
    chatTitle: "مساعد تلاقي الذكي", chatSub: "مستشارك في الشراء", chatOnline: "متصل",
    chatScripted: "محادثة تجريبية", chatLive: "ذكاء حي",
    chatPlaceholder: "وصف اللي تبيه هنا…", chatSend: "إرسال", pickAnswer: "اختر إجابة أو اكتب اللي يناسبك",
    chatStarter1: "أبي متجر إلكتروني لبيع العطور",
    chatStarter2: "أبي هوية بصرية لمشروعي الناشئ",
    chatStarter3: "أبي حملة تسويقية لمنتج جديد",
    chatHello: "هلا فيك في تلاقي 👋 أنا مستشارك الذكي للشراء والتنفيذ. وصف لي اللي تبيه بلغتك العادية، وأنا أحوّله إلى مشروع واضح جاهز للتنفيذ.",
    generateBrief: "توليد الملخص التنفيذي", generating: "نجهّز لك الملخص التنفيذي…",
    genStep1: "تحليل المتطلبات المستخرجة", genStep2: "بناء نطاق العمل والمخرجات", genStep3: "تقدير الميزانية والمدة الزمنية", genStep4: "تحديد معايير التقييم والمراحل",
    liveNote: "وضع الذكاء الحي: تكلّم على راحتك والمساعد يرد عليك مباشرة",
    // brief
    briefKicker: "الملخص التنفيذي للمشروع", briefReady: "جاهز للاعتماد", briefEdit: "تعديل", briefSaveEdit: "حفظ التعديلات",
    briefApprove: "اعتماد الملخص وعرض المرشحين", briefBack: "العودة للمحادثة",
    bSummary: "الملخص", bObjective: "هدف العميل", bScope: "نطاق العمل", bDeliverables: "المخرجات المطلوبة", bSkills: "المهارات المطلوبة",
    bBudget: "الميزانية المقترحة", bTimeline: "مدة التنفيذ المتوقعة", bComplexity: "تعقيد المشروع", bMissing: "أسئلة لا تزال مفتوحة",
    bProviderType: "نوع مقدم الخدمة الموصى به", bCriteria: "معايير التقييم", bMilestones: "المراحل المقترحة",
    briefApprovedToast: "تم اعتماد الملخص التنفيذي ✓",
    // matches
    matchesTitle: "مقدمو الخدمة المرشحون", matchesSub: "رتّبنا لك الأنسب لمشروعك على 7 معايير توافق",
    matchScore: "نسبة التوافق", whyMatch: "ليش هذا الترشيح؟", viewProfile: "عرض الملف", requestProposal: "طلب عرض",
    proposalSent: "تم إرسال طلب العرض ✓", proposalRequested: "بانتظار العرض",
    matchBasis: "نحسب التوافق من: المهارات، التصنيف، الميزانية، الخبرة، التوفر، التقييم، وصلة الأعمال السابقة",
    perProject: "ريال", yearsExp: "سنوات خبرة",
    // provider dash
    pNavHome: "لوحة التحكم", pNavOps: "الفرص المتوافقة", pNavProfile: "ملفي المهني", pNavPortfolio: "الأعمال والخدمات", pNavSettings: "الإعدادات",
    providerWelcome: "هلا عبدالله 👋", providerWelcomeSub: "عندك 3 فرص جديدة تناسب تخصصك",
    pStatOps: "فرص متوافقة", pStatActive: "مشاريع نشطة", pStatRating: "التقييم", pStatResponse: "معدل القبول",
    opsTitle: "الفرص المتوافقة معك", opsSub: "مشاريع موثقة بملخص تنفيذي معتمد من العميل",
    accept: "قبول الفرصة", decline: "اعتذار", accepted: "تم القبول ✓", declined: "تم الاعتذار",
    budgetLabel: "الميزانية", timelineLabel: "المدة", clientLabel: "العميل",
    profileTitle: "ملفي المهني", profileSub: "كل ما كمّلت ملفك، ارتفعت نسبة توافقك مع الفرص",
    profileCompletion: "اكتمال الملف", verifiedBadge: "موثّق ✓",
    pfType: "نوع مقدم الخدمة", pfCity: "المدينة", pfYears: "سنوات الخبرة", pfLangs: "اللغات", pfPrice: "النطاق السعري (ريال)", pfAvail: "التوفر",
    pfSkills: "المهارات", pfServices: "الخدمات", pfPortfolio: "أعمال سابقة", addSkill: "+ إضافة",
    portfolioItems: ["متجر عطور الياسمين — Shopify", "متجر تمور المدينة — WooCommerce", "منصة اشتراكات القهوة — Shopify Plus"],
    servicesItems: ["تطوير متجر إلكتروني متكامل", "تكامل بوابات الدفع السعودية", "ربط أنظمة الشحن المحلية", "تحسين سرعة المتاجر"],
    // admin
    aNavOverview: "نظرة عامة", aNavUsers: "المستخدمون", aNavProviders: "مقدمو الخدمة", aNavProjects: "المشاريع", aNavBriefs: "مراجعة الملخصات", aNavCats: "التصنيفات والمهارات", aNavSettings: "الإعدادات",
    adminTitle: "نظرة عامة على المنصة", adminSub: "آخر تحديث: اليوم 09:41 ص",
    aUsers: "إجمالي المستخدمين", aClients: "العملاء", aProviders: "مقدمو الخدمة", aProjects: "إجمالي المشاريع",
    aWeekly: "مشاريع هذا الأسبوع", aBriefs: "ملخصات مولّدة", aPending: "طلبات انضمام معلّقة", aMatchRate: "نسبة نجاح التوافق",
    aTopCats: "التصنيفات الأكثر طلبًا", aPendingTitle: "طلبات انضمام بانتظار الموافقة", approve: "قبول", reject: "رفض", approvedLbl: "تمت الموافقة ✓", rejectedLbl: "مرفوض",
    aProvidersTitle: "إدارة مقدمي الخدمة", aProjectsTitle: "إدارة المشاريع", thProvider: "مقدم الخدمة", thType: "النوع", thCity: "المدينة", thRating: "التقييم", thVerified: "التوثيق", thPrice: "النطاق السعري",
    verified: "موثّق", unverified: "غير موثّق", thClient: "العميل",
    settingsSoon: "صفحة مبسطة في هذه النسخة التجريبية",
    monthGrowth: "+12% هذا الشهر",
    // nav extras
    navAbout: "عن تلاقي", navClients: "للعملاء", navProviders: "لمقدمي الخدمة", navContact: "تواصل معنا",
    // about
    aboutKicker: "عن تلاقي", aboutTitle: "نغيّر طريقة إنجاز الخدمات المهنية",
    aboutLead: "تلاقي جا من ملاحظة بسيطة: لين الحين الحصول على خدمة مهنية موثوقة رحلة متعبة من البحث والمقارنة والتخمين. إحنا نبني الطبقة الذكية اللي تحوّل احتياجك إلى مشروع واضح، وتوصّله بالخبرة المناسبة.",
    aboutMissionT: "رسالتنا", aboutMission: "نمكّن كل عميل — فرد أو منشأة — من تنفيذ احتياجاته المهنية بوضوح وثقة، ونعطي مقدمي الخدمة فرص أكثر جدية.",
    aboutVisionT: "رؤيتنا", aboutVision: "نطمح نكون نظام التشغيل الذكي للخدمات المهنية في المنطقة، بما ينسجم مع مستهدفات رؤية السعودية 2030 في تنمية الاقتصاد الرقمي وريادة الأعمال.",
    aboutValuesT: "قيم نشتغل فيها",
    aboutVals: [
      { t: "الثقة", d: "توثيق مقدمي الخدمة ومراجعة مستمرة لجودة المخرجات" },
      { t: "الذكاء", d: "قرارات مبنية على فهم عميق للاحتياج وبيانات السوق" },
      { t: "الوضوح", d: "نطاق عمل وميزانية ومدة محددة قبل أي التزام" },
      { t: "السرعة", d: "من الوصف إلى الترشيح في دقايق، مو أسابيع" },
    ],
    // for clients page
    fcKicker: "للعملاء", fcTitle: "من الفكرة إلى التنفيذ بدون تعب",
    fcLead: "ما يلزمك تكون خبير مشتريات. بس وصف اللي تبيه بلغتك، وخلّ تلاقي يتكفّل بالتوصيف والتقدير والترشيح.",
    fcBenefits: [
      { t: "ملخص تنفيذي احترافي", d: "نطاق عمل ومخرجات ومراحل واضحة تحميك من أي لبس بعدين" },
      { t: "تقدير واقعي للميزانية", d: "نطاق سعري مبني على بيانات مشاريع مماثلة في السوق" },
      { t: "ترشيح مُعلَّل", d: "بدون قوائم طويلة — أفضل المرشحين مع سبب واضح لكل ترشيح" },
      { t: "متابعة منظمة", d: "حالة مشروعك ومراحله في لوحة واحدة" },
    ],
    // for providers page
    fpKicker: "لمقدمي الخدمة", fpTitle: "فرص أوضح، وعملاء أكثر جدية",
    fpLead: "انضم لشبكة تلاقي واستقبل مشاريع موثّقة بملخص تنفيذي معتمد — بدون طلبات غامضة ولا مساومات عشوائية.",
    fpBenefits: [
      { t: "طلبات موثقة", d: "كل فرصة توصلك بنطاق عمل وميزانية ومدة محددة من البداية" },
      { t: "توافق ذكي", d: "نرشّح لك بس اللي يناسب مهاراتك وأسعارك وتوفّرك" },
      { t: "وقت أقل في العروض", d: "قدّم عرضك على مشاريع جادة بدال ما تطارد عملاء محتملين" },
      { t: "ملف مهني موثّق", d: "توثيق يرفع موثوقيتك ونسبة ظهورك" },
    ],
    fpSteps: [
      { t: "أنشئ ملفك المهني", d: "خدماتك ومهاراتك وأعمالك ونطاقك السعري" },
      { t: "اجتز التوثيق", d: "مراجعة إدارية تضمن جودة الشبكة" },
      { t: "استقبل الفرص المتوافقة", d: "اقبل اللي يناسبك وأرسل عرضك مباشرة" },
    ],
    // contact
    contactTitle: "تواصل معنا", contactLead: "فريق تلاقي جاهز يجاوب على استفساراتك — عملاء، مقدمي خدمة، أو شركاء.",
    cfName: "الاسم", cfEmail: "البريد الإلكتروني", cfSubject: "الموضوع", cfMessage: "رسالتك",
    cfSend: "إرسال الرسالة", contactSentToast: "تم استلام رسالتك ✓ نرجع لك خلال يوم عمل",
    ciEmail: "البريد الإلكتروني", ciLocation: "المقر", ciLocationV: "الرياض، المملكة العربية السعودية", ciHours: "أوقات العمل", ciHoursV: "الأحد – الخميس، 9ص – 6م",
    // login
    loginTitle: "هلا برجوعك", loginSub: "سجّل دخولك وتابع مشاريعك",
    lfEmail: "البريد الإلكتروني", lfPassword: "كلمة المرور", loginBtn: "تسجيل الدخول", forgotPass: "نسيت كلمة المرور؟",
    loginDemo: "دخول سريع للعرض التجريبي", demoClient: "كعميل", demoProvider: "كمقدم خدمة", demoAdmin: "كمسؤول",
    noAccount: "ما عندك حساب؟", createOne: "أنشئ حساب الحين",
    // signup
    signupTitle: "أنشئ حسابك في تلاقي", signupSub: "دقيقة وحدة وتبدأ",
    suClientT: "أنا عميل", suClientD: "أدوّر خدمة مهنية أنفّذ فيها مشروعي",
    suProviderT: "أنا مقدم خدمة", suProviderD: "أقدّم خدمات مهنية وأدوّر فرص",
    sfName: "الاسم الكامل", sfCompany: "اسم الجهة (اختياري)", sfPhone: "رقم الجوال", sfEmail: "البريد الإلكتروني", sfPassword: "كلمة المرور", sfCity: "المدينة", sfCat: "التخصص الرئيسي",
    signupBtn: "إنشاء الحساب", haveAccount: "عندك حساب من قبل؟", signInLink: "سجّل دخولك",
    termsNote: "بإنشائك الحساب فأنت توافق على الشروط والأحكام وسياسة الخصوصية",
    signupToast: "تم إنشاء حسابك ✓ هلا فيك في تلاقي",
    // project detail
    backToProjects: "→ رجوع لمشاريعي", pdStatusT: "مسار المشروع",
    pdSteps: ["مسودة", "ملخص مولّد", "مرشحون جاهزون", "طلب عروض", "اختيار مقدم"],
    pdBriefT: "لمحة من الملخص التنفيذي", pdViewBrief: "عرض الملخص الكامل ←",
    pdProvidersT: "مقدمو الخدمة", pdNoProviders: "ما طلبت عروض لحد الحين — راجع المرشحين", pdGoMatches: "عرض المرشحين ←",
    pdActivityT: "سجل النشاط",
    pdActivity: [
      { t: "اليوم 10:24 ص", d: "تم ترشيح 6 مقدمي خدمة للمشروع" },
      { t: "اليوم 10:22 ص", d: "اعتمد العميل الملخص التنفيذي" },
      { t: "اليوم 10:15 ص", d: "ولّد الذكاء الاصطناعي الملخص التنفيذي (13 بندًا)" },
      { t: "اليوم 10:08 ص", d: "بدأت محادثة توصيف الاحتياج" },
    ],
    // client profile
    cpTitle: "الملف الشخصي", cpSub: "بيانات جهتك تساعد الذكاء الاصطناعي يوصّف بدقة أكثر",
    cpOrgType: "نوع الجهة", cpOrgTypeV: "شركة صغيرة", cpSector: "القطاع", cpSectorV: "تجزئة — عطور ومستحضرات",
    cpLocation: "الموقع", cpLocationV: "الرياض", cpEmailV: "ahmed@oudalkhaleej.sa", cpPhoneV: "+966 55 123 4567",
    cpContactT: "جهة الاتصال", memberSince: "عضو منذ", memberSinceV: "مارس 2026", cpEdit: "تعديل البيانات",
    // settings
    setLangT: "لغة الواجهة", setLangD: "تنطبق على كل المنصة على طول",
    setNotifT: "الإشعارات",
    notifs: ["بريد إلكتروني عند وصول عرض جديد", "تحديثات حالة المشروع", "نشرة تلاقي الشهرية"],
    setAccountT: "الحساب", changePass: "تغيير كلمة المرور", exportData: "تصدير بياناتي", deleteAcc: "حذف الحساب",
    settingsSaved: "تم الحفظ ✓", demoOnly: "غير متاح في النسخة التجريبية",
    // provider requests
    pNavRequests: "طلبات العروض", requestsTitle: "طلبات العروض الواردة", requestsSub: "عملاء طلبوا عرضك بعد ترشيح الذكاء الاصطناعي",
    reqSend: "إرسال العرض", reqSentLbl: "تم إرسال العرض ✓", reqReceived: "وصل الطلب",
    // admin users
    usersTitle: "إدارة المستخدمين", thUser: "المستخدم", thRole: "الدور", thJoined: "الانضمام",
    roleAdminL: "مسؤول", activeL: "نشط", suspendedL: "موقوف",
    // admin briefs
    briefsTitle: "مراجعة الملخصات المولّدة", briefsSub: "جودة مخرجات الذكاء الاصطناعي تحت إشراف مستمر",
    thQuality: "جودة التوليد", reviewBtn: "مراجعة", closeBtn: "إغلاق", approvedTag: "معتمد", pendingTag: "بانتظار المراجعة",
    // admin analytics
    aNavAnalytics: "تحليلات التوافق", anTitle: "تحليلات التوافق والنشاط", anSub: "أداء محرك الترشيح وإيرادات المنصة",
    anAvgScore: "متوسط نسبة التوافق", anAccept: "معدل قبول الترشيحات", anTime: "متوسط زمن الترشيح",
    anDistT: "توزيع نسب التوافق", anWeeklyT: "مشاريع الأسبوع", anRevT: "الإيرادات والنشاط",
    revMrr: "الإيراد الشهري المتكرر", revSubs: "اشتراكات مدفوعة", revGrowth: "نمو شهري",
    // categories page
    skillsT: "المهارات", addCatBtn: "+ تصنيف", addSkillBtn2: "+ مهارة",
    // decline-with-reason modal (provider)
    declineTitle: "سبب الاعتذار عن الفرصة", declineSub: "سببك يساعدنا نحسّن جودة الترشيحات الجاية",
    declinePlaceholder: "اكتب سبب اعتذارك باختصار… (مثال: خارج نطاق تخصصي، الجدول ما يناسبني، الميزانية ما تناسب)",
    declineConfirm: "تأكيد الاعتذار", declineCancel: "إلغاء", declineReasonRequired: "اكتب سبب الاعتذار من فضلك",
    // visitor chatbot
    botTitle: "مساعد تلاقي", botSub: "اسألني عن المنصة", botOpen: "افتح المساعد الذكي",
    botGreeting: "هلا فيك 👋 أنا مساعد تلاقي. اسألني كيف تشتغل المنصة، عن الاشتراكات، أو كيف تبدأ كعميل أو مقدم خدمة.",
    botPlaceholder: "اكتب سؤالك هنا…", botSend: "إرسال", botError: "ما قدرت أرد الحين — جرّب مرة ثانية بعد شوي.",
    botStarters: ["تلاقي كيف يشتغل؟", "وش باقات الاشتراك؟", "كيف أبدأ كمقدم خدمة؟"],
  },
  en: {
    dir: "ltr", langBtn: "عربي",
    brand: "Talaqi", tagline: "Intelligence that connects you to the right expertise",
    navHow: "How it works", navFeatures: "Features", navCats: "Categories", navPricing: "Subscriptions", login: "Log in", startCta: "Sign up now", joinCta: "Join as a provider",
    heroBadge: "AI Procurement & Execution Platform — تلاقي",
    heroTitle1: "Just describe your need —", heroTitle2: "AI handles the rest",
    heroSub: "Talaqi turns your service needs into clear, executable projects, then matches you with the most suitable provider — no searching, no comparing, no guesswork.",
    heroSubEn: "تلاقي: صف احتياجك فقط، والذكاء الاصطناعي يتولى الباقي.",
    pipe1: "Describe", pipe2: "AI understands", pipe3: "Project brief", pipe4: "Smart match", pipe5: "Execute",
    statBriefs: "briefs generated", statProviders: "verified providers", statMatch: "matching accuracy",
    problemTitle: "The traditional way wastes your time", problemSub: "Today's marketplaces put the entire burden on the client",
    problems: ["Manually searching hundreds of freelancers and firms", "Comparing prices and reading reviews one by one", "Writing project specs and estimating budgets without expertise", "Choosing alone and carrying all execution risk"],
    solutionTitle: "Talaqi flips the equation", solutionSub: "A new journey that starts with understanding and ends with execution",
    oldJourney: "The old journey", newJourney: "The Talaqi journey",
    oldSteps: "Search → Compare → Choose", newSteps: "Describe → AI Understands → AI Matches → Execute",
    positioning: "Talaqi is the intelligent operating system for professional services — from understanding your need to recommending the right provider.",
    howTitle: "How Talaqi works", howSub: "Five steps from idea to execution",
    how: [
      { t: "Describe your need", d: "Write what you need in plain language — no jargon" },
      { t: "Smart questions", d: "AI asks focused questions to complete the picture" },
      { t: "Professional brief", d: "Clear scope, budget, timeline and evaluation criteria" },
      { t: "Best-fit recommendations", d: "The matching engine ranks providers with a score and reason" },
      { t: "Execute with clarity", d: "A documented project with defined milestones from day one" },
    ],
    valueTitle: "Clear value for both sides",
    forClients: "For clients", forProviders: "For providers",
    clientVals: ["Less effort, more time", "Clear scope from the start", "Sharper provider selection", "Lower risk, faster execution"],
    providerVals: ["Clear, documented project requests", "Opportunities matched to your specialty", "Less time wasted on dead-end bids", "More serious clients"],
    featuresTitle: "A complete AI-powered system", featuresSub: "From understanding the need to recommending the best fit",
    features: [
      { t: "AI Requirement Analysis", d: "Deep understanding from a simple description" },
      { t: "Project Brief Generator", d: "A professional 13-item project brief" },
      { t: "Scope of Work Builder", d: "Specific, measurable tasks and deliverables" },
      { t: "Budget Estimator", d: "Realistic price ranges from market data" },
      { t: "Timeline Estimator", d: "Clear execution schedule and phases" },
      { t: "Smart Matching Engine", d: "Ranked recommendations with reasons" },
      { t: "Provider Profiles", d: "Verified experience, portfolios and ratings" },
      { t: "Admin Review Dashboard", d: "Output quality under continuous oversight" },
    ],
    catsTitle: "Service categories", catsSub: "16 professional categories covering business needs", catProject: "projects",
    pricingTitle: "Plans for every stage", pricingSub: "Start free, upgrade when you need to",
    plans: [
      { n: "Free", p: "0", per: "SAR/mo", feats: ["Basic project request", "Simple AI brief", "Limited recommendations"], cta: "Start free", hot: false },
      { n: "Pro Client", p: "99", per: "SAR/mo", feats: ["Advanced AI brief", "Budget & timeline estimation", "More recommendations", "Priority matching"], cta: "Subscribe", hot: true },
      { n: "Business", p: "349", per: "SAR/mo", feats: ["Multiple projects", "Team access", "Advanced dashboard", "AI procurement assistant", "Dedicated support"], cta: "Contact us", hot: false },
      { n: "Provider Pro", p: "149", per: "SAR/mo", feats: ["Enhanced profile", "More visibility", "Matching insights", "Portfolio optimization"], cta: "Join now", hot: false },
    ],
    popular: "Most popular",
    closingTitle: "Start now — turn your idea into a clear, executable project",
    closingSub: "You're minutes away from a professional brief and the right provider",
    footerRights: "© 2026 Talaqi — All rights reserved", footerMade: "Made in Saudi Arabia 🇸🇦",
    footerLinks1: "Platform", footerLinks2: "Company", footerAbout: "About Talaqi", footerContact: "Contact", footerTerms: "Terms", footerPrivacy: "Privacy",
    roleClient: "Client", roleProvider: "Provider", roleAdmin: "Admin", backToSite: "Public site", demoMode: "Demo build",
    cNavHome: "Dashboard", cNavNew: "New project", cNavBrief: "Project Brief", cNavMatches: "Recommended providers", cNavProjects: "My projects", cNavSettings: "Settings",
    clientName: "Oud Al-Khaleej Co.", clientPerson: "Ahmed Al-Mutairi",
    welcome: "Welcome, Ahmed 👋", welcomeSub: "Let's turn your next need into a clear project",
    statActive: "Active projects", statBriefsDone: "Briefs generated", statProposals: "Proposals received", statSaved: "Hours saved",
    newProjectCta: "Start a new project", newProjectSub: "Describe your need — AI handles the rest",
    myProjects: "My projects", viewAll: "View all",
    thProject: "Project", thCategory: "Category", thBudget: "Budget (SAR)", thTimeline: "Timeline", thStatus: "Status", thDate: "Date",
    stDraft: "Draft", stBrief: "Brief generated", stMatched: "Providers ready", stSelected: "Provider selected", stInprogress: "In progress", stCompleted: "Completed",
    chatTitle: "Talaqi AI Assistant", chatSub: "Your procurement consultant", chatOnline: "Online",
    chatScripted: "Demo conversation", chatLive: "Live AI",
    chatPlaceholder: "Describe your need…", chatSend: "Send", pickAnswer: "Pick an answer or type your own",
    chatStarter1: "I need an online store to sell perfumes",
    chatStarter2: "I need a brand identity for my startup",
    chatStarter3: "I need a marketing campaign for a new product",
    chatHello: "Welcome to Talaqi 👋 I'm your AI procurement consultant. Describe your need in plain language and I'll turn it into a clear, executable project.",
    generateBrief: "Generate Project Brief", generating: "Generating your Project Brief…",
    genStep1: "Analyzing extracted requirements", genStep2: "Building scope of work & deliverables", genStep3: "Estimating budget & timeline", genStep4: "Defining evaluation criteria & milestones",
    liveNote: "Live AI mode: chat freely — the assistant replies in real time",
    briefKicker: "Project Brief", briefReady: "Ready for approval", briefEdit: "Edit", briefSaveEdit: "Save changes",
    briefApprove: "Approve & view recommendations", briefBack: "Back to chat",
    bSummary: "Summary", bObjective: "Client objective", bScope: "Scope of work", bDeliverables: "Required deliverables", bSkills: "Required skills",
    bBudget: "Suggested budget", bTimeline: "Expected timeline", bComplexity: "Project complexity", bMissing: "Open questions",
    bProviderType: "Recommended provider type", bCriteria: "Evaluation criteria", bMilestones: "Suggested milestones",
    briefApprovedToast: "Project Brief approved ✓",
    matchesTitle: "Recommended providers", matchesSub: "Ranked for your project across 7 matching criteria",
    matchScore: "Match", whyMatch: "Why this recommendation?", viewProfile: "View profile", requestProposal: "Request proposal",
    proposalSent: "Proposal requested ✓", proposalRequested: "Awaiting proposal",
    matchBasis: "Match score weighs: skills, category, budget fit, experience, availability, rating and portfolio relevance",
    perProject: "SAR", yearsExp: "yrs experience",
    pNavHome: "Dashboard", pNavOps: "Matched opportunities", pNavProfile: "My profile", pNavPortfolio: "Services & portfolio", pNavSettings: "Settings",
    providerWelcome: "Welcome, Abdullah 👋", providerWelcomeSub: "You have 3 new opportunities matched to your specialty",
    pStatOps: "Matched opportunities", pStatActive: "Active projects", pStatRating: "Rating", pStatResponse: "Acceptance rate",
    opsTitle: "Opportunities matched to you", opsSub: "Documented projects with client-approved briefs",
    accept: "Accept", decline: "Decline", accepted: "Accepted ✓", declined: "Declined",
    budgetLabel: "Budget", timelineLabel: "Timeline", clientLabel: "Client",
    profileTitle: "My professional profile", profileSub: "A complete profile raises your match scores",
    profileCompletion: "Profile completion", verifiedBadge: "Verified ✓",
    pfType: "Provider type", pfCity: "City", pfYears: "Years of experience", pfLangs: "Languages", pfPrice: "Price range (SAR)", pfAvail: "Availability",
    pfSkills: "Skills", pfServices: "Services", pfPortfolio: "Portfolio", addSkill: "+ Add",
    portfolioItems: ["Yasmine Perfumes store — Shopify", "Madinah Dates store — WooCommerce", "Coffee subscriptions platform — Shopify Plus"],
    servicesItems: ["Full e-commerce store development", "Saudi payment gateways integration", "Local shipping systems integration", "Store speed optimization"],
    aNavOverview: "Overview", aNavUsers: "Users", aNavProviders: "Providers", aNavProjects: "Projects", aNavBriefs: "Briefs review", aNavCats: "Categories & skills", aNavSettings: "Settings",
    adminTitle: "Platform overview", adminSub: "Last updated: today 09:41 AM",
    aUsers: "Total users", aClients: "Clients", aProviders: "Providers", aProjects: "Total projects",
    aWeekly: "Projects this week", aBriefs: "AI briefs generated", aPending: "Pending approvals", aMatchRate: "Matching success rate",
    aTopCats: "Most requested categories", aPendingTitle: "Providers awaiting approval", approve: "Approve", reject: "Reject", approvedLbl: "Approved ✓", rejectedLbl: "Rejected",
    aProvidersTitle: "Providers management", aProjectsTitle: "Projects management", thProvider: "Provider", thType: "Type", thCity: "City", thRating: "Rating", thVerified: "Status", thPrice: "Price range",
    verified: "Verified", unverified: "Unverified", thClient: "Client",
    settingsSoon: "Simplified page in this demo build",
    monthGrowth: "+12% this month",
    navAbout: "About", navClients: "For clients", navProviders: "For providers", navContact: "Contact",
    aboutKicker: "About Talaqi", aboutTitle: "Redefining how professional services get done",
    aboutLead: "Talaqi was born from a simple observation: getting reliable professional services is still an exhausting journey of searching, comparing and guessing. We're building the intelligent layer that turns a need into a clear project and connects it with the right expertise.",
    aboutMissionT: "Our mission", aboutMission: "Enable every client — individual or organization — to execute their professional needs with clarity and confidence, and give providers more serious opportunities.",
    aboutVisionT: "Our vision", aboutVision: "To become the region's intelligent operating system for professional services, aligned with Saudi Vision 2030's digital economy and entrepreneurship goals.",
    aboutValuesT: "Values we work by",
    aboutVals: [
      { t: "Trust", d: "Verified providers and continuous output quality review" },
      { t: "Intelligence", d: "Decisions built on deep need understanding and market data" },
      { t: "Clarity", d: "Defined scope, budget and timeline before any commitment" },
      { t: "Speed", d: "From description to shortlist in minutes, not weeks" },
    ],
    fcKicker: "For clients", fcTitle: "From idea to execution, effortlessly",
    fcLead: "You don't need to be a procurement expert. Describe your need in your own words — Talaqi handles scoping, estimation and matching.",
    fcBenefits: [
      { t: "A professional brief", d: "Clear scope, deliverables and milestones that protect you from ambiguity" },
      { t: "Realistic budget estimates", d: "Price ranges built from similar market projects" },
      { t: "Explained recommendations", d: "No long lists — top candidates with a clear reason for each" },
      { t: "Organized tracking", d: "Your project status and milestones in one dashboard" },
    ],
    fpKicker: "For providers", fpTitle: "Clearer opportunities, more serious clients",
    fpLead: "Join the Talaqi network and receive documented projects with client-approved briefs — no vague requests, no random haggling.",
    fpBenefits: [
      { t: "Documented requests", d: "Every opportunity arrives with predefined scope, budget and timeline" },
      { t: "Smart matching", d: "We only recommend what fits your skills, rates and availability" },
      { t: "Less time on bids", d: "Propose on serious projects instead of chasing leads" },
      { t: "A verified profile", d: "Verification raises your credibility and visibility" },
    ],
    fpSteps: [
      { t: "Create your profile", d: "Your services, skills, portfolio and price range" },
      { t: "Get verified", d: "An admin review that keeps the network high-quality" },
      { t: "Receive matched opportunities", d: "Accept what fits and send your proposal directly" },
    ],
    contactTitle: "Contact us", contactLead: "The Talaqi team is ready to answer your questions — clients, providers or partners.",
    cfName: "Name", cfEmail: "Email", cfSubject: "Subject", cfMessage: "Your message",
    cfSend: "Send message", contactSentToast: "Message received ✓ We'll reply within one business day",
    ciEmail: "Email", ciLocation: "Headquarters", ciLocationV: "Riyadh, Saudi Arabia", ciHours: "Working hours", ciHoursV: "Sun – Thu, 9am – 6pm",
    loginTitle: "Welcome back", loginSub: "Sign in to continue your projects",
    lfEmail: "Email", lfPassword: "Password", loginBtn: "Log in", forgotPass: "Forgot password?",
    loginDemo: "Quick demo access", demoClient: "As client", demoProvider: "As provider", demoAdmin: "As admin",
    noAccount: "No account?", createOne: "Create one now",
    signupTitle: "Create your Talaqi account", signupSub: "One minute and you're in",
    suClientT: "I'm a client", suClientD: "Looking for a professional service",
    suProviderT: "I'm a provider", suProviderD: "Offering professional services",
    sfName: "Full name", sfCompany: "Organization (optional)", sfPhone: "Mobile number", sfEmail: "Email", sfPassword: "Password", sfCity: "City", sfCat: "Main specialty",
    signupBtn: "Create account", haveAccount: "Already have an account?", signInLink: "Sign in",
    termsNote: "By creating an account you agree to the Terms and Privacy Policy",
    signupToast: "Account created ✓ Welcome to Talaqi",
    backToProjects: "← Back to my projects", pdStatusT: "Project journey",
    pdSteps: ["Draft", "Brief generated", "Providers ready", "Proposals requested", "Provider selected"],
    pdBriefT: "Brief snapshot", pdViewBrief: "View full brief →",
    pdProvidersT: "Providers", pdNoProviders: "No proposals requested yet — review your matches", pdGoMatches: "View matches →",
    pdActivityT: "Activity log",
    pdActivity: [
      { t: "Today 10:24 AM", d: "6 providers recommended for the project" },
      { t: "Today 10:22 AM", d: "Client approved the Project Brief" },
      { t: "Today 10:15 AM", d: "AI generated the Project Brief (13 items)" },
      { t: "Today 10:08 AM", d: "Requirement conversation started" },
    ],
    cpTitle: "My profile", cpSub: "Your organization data helps the AI scope more accurately",
    cpOrgType: "Organization type", cpOrgTypeV: "Small company", cpSector: "Sector", cpSectorV: "Retail — perfumes & cosmetics",
    cpLocation: "Location", cpLocationV: "Riyadh", cpEmailV: "ahmed@oudalkhaleej.sa", cpPhoneV: "+966 55 123 4567",
    cpContactT: "Contact person", memberSince: "Member since", memberSinceV: "March 2026", cpEdit: "Edit details",
    setLangT: "Interface language", setLangD: "Applies across the platform instantly",
    setNotifT: "Notifications",
    notifs: ["Email when a new proposal arrives", "Project status updates", "Talaqi monthly newsletter"],
    setAccountT: "Account", changePass: "Change password", exportData: "Export my data", deleteAcc: "Delete account",
    settingsSaved: "Saved ✓", demoOnly: "Not available in this demo build",
    pNavRequests: "Proposal requests", requestsTitle: "Incoming proposal requests", requestsSub: "Clients who requested your proposal after AI matching",
    reqSend: "Send proposal", reqSentLbl: "Proposal sent ✓", reqReceived: "Received",
    usersTitle: "Users management", thUser: "User", thRole: "Role", thJoined: "Joined",
    roleAdminL: "Admin", activeL: "Active", suspendedL: "Suspended",
    briefsTitle: "AI briefs review", briefsSub: "AI output quality under continuous oversight",
    thQuality: "Generation quality", reviewBtn: "Review", closeBtn: "Close", approvedTag: "Approved", pendingTag: "Pending review",
    aNavAnalytics: "Matching analytics", anTitle: "Matching & activity analytics", anSub: "Matching engine performance and platform revenue",
    anAvgScore: "Average match score", anAccept: "Recommendation acceptance", anTime: "Average time to match",
    anDistT: "Match score distribution", anWeeklyT: "Projects this week", anRevT: "Revenue & activity",
    revMrr: "Monthly recurring revenue", revSubs: "Paid subscriptions", revGrowth: "Monthly growth",
    skillsT: "Skills", addCatBtn: "+ Category", addSkillBtn2: "+ Skill",
    // decline-with-reason modal (provider)
    declineTitle: "Reason for declining", declineSub: "Your reason helps us improve future recommendations",
    declinePlaceholder: "Briefly, why are you declining? (e.g. outside my specialty, timeline doesn't fit, budget too low)",
    declineConfirm: "Confirm decline", declineCancel: "Cancel", declineReasonRequired: "Please provide a reason",
    // visitor chatbot
    botTitle: "Talaqi Assistant", botSub: "Ask me about the platform", botOpen: "Open the assistant",
    botGreeting: "Hi 👋 I'm the Talaqi assistant. Ask me how the platform works, about subscriptions, or how to start as a client or provider.",
    botPlaceholder: "Type your question…", botSend: "Send", botError: "Couldn't respond right now — please try again shortly.",
    botStarters: ["How does Talaqi work?", "What are the subscription plans?", "How do I start as a provider?"],
  },
};
